#!/usr/bin/python3

//second merge conflict
def main(msg):
    print(msg)

main("Hello git")
